falas = {
    "Se você deseja jogar comigo, é melhor ter certeza de que conhece o jogo.": "ahri", 
    "Eles podem ter muitos, mas você tem eu.": "braum",
    "Eu vou levar você e sua confissão para a delegacia.": "caitlyn",
    "Aqui é onde eu entro.": "camille",
    "Eu serei ouvida!": "diana",
    "Um homem, uma mulher e um yordle caminham sobre o sol. Eles morrem. E o sol os queima vivos. Hahahah!": "diana",
    "Eu não sou um monstro, eu sou um dragão!": "shyvana",
    "O dia de alguém tá prestes a ser detonado.": "ekko",
    "Me engane uma vez, e eu só vou rebobinar.": "ekko",
    "Ain, esse lugar é tão sem graça… Vou dar um toque de vermelho!": "evelynn",
    "Não tenho exatamente “amigos”, só gente que eu ainda não destripei!": "evelynn",
    "Huh?! Aquilo atrás dos penhascos são… Montanhas?! Eu sempre quis ver uma de perto!": "gwen",
    "42… Eu sei que esse número significa algo.": "heimerdinger",
    "Traga o martelo!": "jayce",
    "Acha que EU sou louca? Você devia conhecer a minha irmã.": "jinx",
    "Três armas é igual a nunca ter que pedir desculpas.": "jinx",
    "Sinta a glória solar.": "leona",
    "Seres quietinhos são fortes. Por isso eu tô falando baixinho!": "lillia",
    "Quando dizem “boa noite” é de verdade, ou só um tchau?": "lillia",
    "Todo mundo morre… Alguns só precisam de uma ajudinha.": "lucian",
    "Coitados… Não sabem que vão comigo pro inferno.": "lucian",
    "Olha essa boca, garoto… Ou mando você ressurgir direto pra casa.": "miss fortune",
    "Nas horas vagas, eu sou uma encantadora de tubarões.": "nami",
    "Medinho de molhar os pés?": "nami",
    "Olha, eu até tentei ser bom… Mas a maldade combina tanto com esse rostinho bonito…": "rakan",
    "Quem precisa de amor quando se tem uma capa feita de facas de matéria escura?": "xayah",
    "A névoa sabe meu nome. Passou anos gritando por mim. Mas ela só queria ajuda…": "senna",
    "Aquele monstro quer me ouvir gritar? Pode esperar sentado…": "senna",
    "O chefe tá na área! Sem aplauso… Sério, xiu aí.": "sett",
    "Olha, você não conhece ninguém de verdade até lutar com eles até a morte.": "sett"
}