personagens = {
    "aatrox": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Darkin",
        "Recurso" : "Sem Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Runeterra, Shurima",
        "Ano de Lancamento" : "2013",
    },
    "ahri": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : "Vastaya",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2011",
    },
    "akali": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : "Humano",
        "Recurso" : "Energia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2010",
    },
    "akshan": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2021",
    },
    "alistar": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : "Minotauro",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2009",
    },
    "amumu": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : ["Yordle", "Morto-Vivo"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2009",
    },
    "anivia": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Deus, Espirito"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2009",
    },
    "annie": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Noxus", "Runeterra"],
        "Ano de Lancamento" : "2009",
    },
    "aphelios": {
        "Genero" : "Homem",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Targon",
        "Ano de Lancamento" : "2019",
    },
    "ashe": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Glacinata"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2009",
    },
    "aphelios": {
        "Genero" : "Homem",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Targon",
        "Ano de Lancamento" : "2019",
    },
    "aurelion sol": {
        "Genero" : "Homem",
        "Posicao" : "Meio",
        "Especie" : ["Celestial", "Dragão"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Targon", "Runeterra"],
        "Ano de Lancamento" : "2016",
    },
    "azir": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : "Deus Guerreiro",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Shrurima",
        "Ano de Lancamento" : "2014",
    },
    "bardo": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : "Celestial",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2015",
    },
    "belveth": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : "Cria do Vazio",
        "Recurso" : "Sem Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Vazio",
        "Ano de Lancamento" : "2022",
    },
    "blitzcrank": {
        "Genero" : "Outro",
        "Posicao" : "Suporte",
        "Especie" : "Golem",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2009",
    },
    "brand": {
        "Genero" : "Homem",
        "Posicao" : ["Jungle", "Suporte"],
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Freljord", "Runeterra"],
        "Ano de Lancamento" : "2011",
    },
    "braum": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Glacinata"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2014",
    },
    "briar": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : "Golem",
        "Recurso" : "Custos de Vida",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2023",
    },
    "cailtyn": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Piltover",
        "Ano de Lancamento" : "2011",
    },
    "camille": {
        "Genero" : "Mulher",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Ciborgue"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Piltover",
        "Ano de Lancamento" : "2016",
    },
    "cassiopeia": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Noxus", "Shurima"],
        "Ano de Lancamento" : "2010",
    },
    "chogath": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Cria do Vazio",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Vazio",
        "Ano de Lancamento" : "2009",
    },
    "corki": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Piltover", "Bandopolis"],
        "Ano de Lancamento" : "2009",
    },
    "darius": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2012",
    },
    "diana": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Aspecto"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Targon",
        "Ano de Lancamento" : "2012",
    },
    "dr mundo": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Quimicamente Alterado"],
        "Recurso" : "Custos de Vida",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2009",
    },
    "draven": {
        "Genero" : "Homem",
        "Posicao" : "ADC",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2012",
    },
    "diana": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Aspecto"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Targon",
        "Ano de Lancamento" : "2012",
    },
    "ekko": {
        "Genero" : "Homem",
        "Posicao" : ["Jungle", "Mid"],
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2015",
    },
    "elise": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : ["Corpo a Corpo", "Longo Alcance"],
        "Regiao" : ["Noxus", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2012",
    },
    "evelynn": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : ["Demonio", "Espirito"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2009",
    },
    "ezreal": {
        "Genero" : "Homem",
        "Posicao" : "Atirador",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Piltover",
        "Ano de Lancamento" : "2010",
    },
    "nunu e willump": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Yeti"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2009",
    },
    "fiddlesticks": {
        "Genero" : "Outro",
        "Posicao" : "Jungle",
        "Especie" : ["Demonio", "Espirito"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : ["Longo Alcance", "Corpo a Corpo"],
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2009",
    },
    "fiora": {
        "Genero" : "Mulher",
        "Posicao" : "Top",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Demacia",
        "Ano de Lancamento" : "2012",
    },
    "fizz": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Aguas de Sentina",
        "Ano de Lancamento" : "2011",
    },
    "miss fortune": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Aguas de Sentina",
        "Ano de Lancamento" : "2010",
    },
    "twisted fate": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Aguas de Sentina",
        "Ano de Lancamento" : "2009",
    },
    "galio": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : "Golem",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Demacia",
        "Ano de Lancamento" : "2010",
    },
    "gangplank": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Aguas de Sentina",
        "Ano de Lancamento" : "2009",
    },
    "garen": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Humano",
        "Recurso" : "Sem Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Demacia",
        "Ano de Lancamento" : "2010",
    },
    "gnar": {
        "Genero" : "Homem",
        "Posicao" : "Topp",
        "Especie" : "Yordle",
        "Recurso" : "Furia",
        "Tipo de Alcance" : ["Corpo a Corpo", "Longo Alcance"],
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2014",
    },
    "gragas": {
        "Genero" : "Homem",
        "Posicao" : ["Jungle", "Top"],
        "Especie" : ["Humano", "Glacinata"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2010",
    },
    "graves": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Aguas de Sentina",
        "Ano de Lancamento" : "2011",
    },
    "gwen": {
        "Genero" : "Mulher",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Camavor", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2021",
    },
    "Renata Glasc": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : ["Quimicamente Alterado", "Humano"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2022",
    },
    "hecarim": {
        "Genero" : "Homen",
        "Posicao" : "Jungle",
        "Especie" : "Morto Vivo",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Camavor", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2012",
    },
    "heimerdinger": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "Top"],
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Piltover",
        "Ano de Lancamento" : "2009",
    },
    "hwei": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2023",
    },
    "illaoi": {
        "Genero" : "Mulher",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Aguas de Sentina",
        "Ano de Lancamento" : "2015",
    },
    "irelia": {
        "Genero" : "Mulher",
        "Posicao" : ["Top", "Mid"],
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2010",
    },
    "ivern": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Ionia", "Freljord"],
        "Ano de Lancamento" : "2016",
    },
    "jarvan iv": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Demacia",
        "Ano de Lancamento" : "2011",
    },
    "ksante": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2022",
    },
    "kaisa": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Cria do Vazio"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Vazio", "Shurima"],
        "Ano de Lancamento" : "2018",
    },
    "kalista": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : "Morto Vivo",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Ilhas das Sombras", "Camavor"],
        "Ano de Lancamento" : "2014",
    },
    "karma": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2011",
    },
    "karthus": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Morto Vivo",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Noxus", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2009",
    },
    "kassadin": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Cria do Vazio"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Vazio", "Shurima"],
        "Ano de Lancamento" : "2009",
    },
    "katarina": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : "Humano",
        "Recurso" : "Sem Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2009",
    },
    "kayle": {
        "Genero" : "Mulher",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Aspecto", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : ["Longo Alcance", "Corpo a Corpo"],
        "Regiao" : ["Demacia", "Targon"],
        "Ano de Lancamento" : "2009",
    },
    "kayn": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Darkin", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Runeterra", "Ionia", "Noxus", "Shurima"],
        "Ano de Lancamento" : "2017",
    },
    "kennen": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Yordle",
        "Recurso" : "Energia",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2010",
    },
    "khazix": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Cria do Vazio",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Vazio",
        "Ano de Lancamento" : "2012",
    },
    "kindred": {
        "Genero" : "Outro",
        "Posicao" : "Jungle",
        "Especie" : ["Deus", "Espirito"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2015",
    },
    "kled": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Yordle",
        "Recurso" : "Coragem",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2016",
    },
    "kogmaw": {
        "Genero" : "Homem",
        "Posicao" : "ADC",
        "Especie" : "Cria do Vazio",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Vazio",
        "Ano de Lancamento" : "2010",
    },
    "tahm kench": {
        "Genero" : "Homem",
        "Posicao" : ["Suporte", "Top"],
        "Especie" : ["Demonio", "Espirito"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Aguas de Sentina", "Runeterra"],
        "Ano de Lancamento" : "2015",
    },
    "leblanc": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2010",
    },
    "lee sin": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Energia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2011",
    },
    "leona": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Aspecto"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Targon",
        "Ano de Lancamento" : "2011",
    },
    "lillia": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : "Espirito",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2020",
    },
    "lissandra": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Glacinata"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2013",
    },
    "lucian": {
        "Genero" : "Homem",
        "Posicao" : "ADC",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Demacia", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2013",
    },
    "lulu": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Bandopolis",
        "Ano de Lancamento" : "2012",
    },
    "lux": {
        "Genero" : "Mulher",
        "Posicao" : ["Mid", "Suporte"],
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Demacia",
        "Ano de Lancamento" : "2010",
    },
    "malphite": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Golem",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Ixtal", "Shurima"],
        "Ano de Lancamento" : "2009",
    },
    "malzahar": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : ["Cria do Vazio", "Humano"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Vazio", "Shurima"],
        "Ano de Lancamento" : "2010",
    },
    "maokai": {
        "Genero" : "Homem",
        "Posicao" : ["Jungle", "Suporte"],
        "Especie" : "Espirito",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ilhas das Sombras",
        "Ano de Lancamento" : "2011",
    },
    "master yi": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2009",
    },
    "milio": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ixtal",
        "Ano de Lancamento" : "2023",
    },
    "mordekaiser": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Revena",
        "Recurso" : "Escudo",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Noxus", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2010",
    },
    "morgana": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Aspecto", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Demacia", "Targon"],
        "Ano de Lancamento" : "2009",
    },
    "naafiri": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Darkin", "Cachorro"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2023",
    },
    "nami": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : "Vastaya",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Aguas de Sentina", "Runeterra"],
        "Ano de Lancamento" : "2012",
    },
    "nasus": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Deus Guerreiro",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2009",
    },
    "nautilus": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : "Revena",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Aguas de Sentina",
        "Ano de Lancamento" : "2012",
    },
    "neeko": {
        "Genero" : "Mulher",
        "Posicao" : ["Mid", "Suporte"],
        "Especie" : "Vastaya",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ixtal",
        "Ano de Lancamento" : "2018",
    },
    "nidalee": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : ["Longo Alcance", "Corpo a Corpo"],
        "Regiao" : "Ixtal",
        "Ano de Lancamento" : "2009",
    },
    "nilah": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Aguas de Sentina",
        "Ano de Lancamento" : "2022",
    },
    "nocturne": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : ["Demonio", "Espirito"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2011",
    },
    "olaf": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Glacinata"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2010",
    },
    "orianna": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : "Golem",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Piltover",
        "Ano de Lancamento" : "2011",
    },
    "ornn": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : ["Deus", "Espirito"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2017",
    },
    "pantheon": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "Top", "Suporte"],
        "Especie" : ["Humano", "Aspecto"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Targon",
        "Ano de Lancamento" : "2010",
    },
    "poppy": {
        "Genero" : "Mulher",
        "Posicao" : ["Top", "Suporte", "Jungle"],
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Demacia",
        "Ano de Lancamento" : "2010",
    },
    "pyke": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : "Revena",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Aguas de Sentina",
        "Ano de Lancamento" : "2018",
    },
    "qiyana": {
        "Genero" : "Mulher",
        "Posicao" : ["Mid", "Jungle"],
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ixtal",
        "Ano de Lancamento" : "2019",
    },
    "quinn": {
        "Genero" : "Mulher",
        "Posicao" : "Top",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Demacia",
        "Ano de Lancamento" : "2013",
    },
    "rakan": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : "Vastaya",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2017",
    },
    "rammus": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Desconhecido",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2009",
    },
    "reksai": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : "Cria do Vazio",
        "Recurso" : "Furia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Vazio", "Shurima"],
        "Ano de Lancamento" : "2014",
    },
    "rell": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Alterado Magicamente", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2020",
    },
    "renekton": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Deus Guerreiro",
        "Recurso" : "Furia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2011",
    },
    "rengar": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Vastaya",
        "Recurso" : "Ferocidade",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Ixtal", "Shurima"],
        "Ano de Lancamento" : "2012",
    },
    "riven": {
        "Genero" : "Mulher",
        "Posicao" : "Top",
        "Especie" : "Humano",
        "Recurso" : "Sem Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Noxus", "Ionia"],
        "Ano de Lancamento" : "2011",
    },
    "rumble": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Yordle",
        "Recurso" : "Aquecimento",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Bandopolis",
        "Ano de Lancamento" : "2011",
    },
    "ryze": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2009",
    },
    "samira": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Shurima", "Noxus"],
        "Ano de Lancamento" : "2020",
    },
    "sejuani": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Glacinata"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2012",
    },
    "senna": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Morto Vivo"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ilhas das Sombras",
        "Ano de Lancamento" : "2019",
    },
    "seraphine": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Piltover", "Zaun"],
        "Ano de Lancamento" : "2020",
    },
    "sett": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Vastaya"],
        "Recurso" : "Ousadia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2020",
    }, 
    "shaco": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Espirito",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2009",
    },
    "shen": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Energia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2009",
    },
    "shyvana": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : ["Dragao", "Alterado Magicamente"],
        "Recurso" : "Furia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Demacia",
        "Ano de Lancamento" : "2011",
    },
    "singed": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Quiimicamente Alterado"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Piltover", "Zaun"],
        "Ano de Lancamento" : "2009",
    },
    "sion": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Revena",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2009",
    },
    "sivir": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2009",
    },
    "skarner": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Brackern",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ixtal",
        "Ano de Lancamento" : "2011",
    },
    "smolder": {
        "Genero" : "Homem",
        "Posicao" : "Atirador",
        "Especie" : "Dragao",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Camavor", "Noxus"],
        "Ano de Lancamento" : "2024",
    },
    "sona": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Demacia", "Ionia"],
        "Ano de Lancamento" : "2010",
    },
    "soraka": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : "Celestial",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Ionia", "Targon"],
        "Ano de Lancamento" : "2009",
    },
    "swain": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2010",
    },
    "sylas": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Demacia", "Freljord"],
        "Ano de Lancamento" : "2019",
    },
    "syndra": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2012",
    },
    "taliyah": {
        "Genero" : "Homem",
        "Posicao" : ["Jungle", "Mid"],
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2016",
    },
    "talon": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "Jungle"],
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2011",
    },
    "taric": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Aspecto"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Targon", "Demacia"],
        "Ano de Lancamento" : "2009",
    },
    "teemo": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Bandopolis",
        "Ano de Lancamento" : "2009",
    },
    "thresh": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : "Morto Vivo",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ilhas das Sombras",
        "Ano de Lancamento" : "2013",
    },
    "tristana": {
        "Genero" : "Mulher",
        "Posicao" : ["ADC", "Mid"],
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Bandopolis",
        "Ano de Lancamento" : "2009",
    },
    "trundle": {
        "Genero" : "Homem",
        "Posicao" : ["Top", "Jungle"],
        "Especie" : ["Troll", "Glacinata"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2010",
    },
    "tryndamere": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Furia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2009",
    },
    "twitch": {
        "Genero" : "Homem",
        "Posicao" : "ADC",
        "Especie" : ["Rato", "Quimicamente Alterado"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2009",
    },
    "udyr": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Freljord", "Ionia"],
        "Ano de Lancamento" : "2009",
    },
    "urgot": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Quimicamente Alterado", "Ciborgue"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Zaun", "Noxus"],
        "Ano de Lancamento" : "2010",
    },
    "varus": {
        "Genero" : "Homem",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Darkin"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Ionia", "Shurima", "Runeterra"],
        "Ano de Lancamento" : "2012",
    },
    "vayne": {
        "Genero" : "Mulher",
        "Posicao" : ["ADC", "Top"],
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Demacia",
        "Ano de Lancamento" : "2011",
    },
    "veigar": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Bandopolis", "Runeterra", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2009",
    },
    "velkoz": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "Suporte"],
        "Especie" : "Cria do Vazio",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Vazio",
        "Ano de Lancamento" : "2014",
    },
    "vex": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Bandopolis", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2021",
    },
    "vi": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Piltover", "Zaun"],
        "Ano de Lancamento" : "2012",
    },
    "viego": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Humano",
        "Recurso" : "Sem Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Camavor", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2021",
    },
    "viktor": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Ciborgue"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Piltover", "Zaun"],
        "Ano de Lancamento" : "2011",
    },
    "vladimir": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "Top"],
        "Especie" : ["Alterado Magicamente", "Humano"],
        "Recurso" : "Impeto Vermelho",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Noxus", "Camavor", "Ilhas das Sombras"],
        "Ano de Lancamento" : "2010",
    },
    "volibear": {
        "Genero" : "Homem",
        "Posicao" : ["Top", "Jungle"],
        "Especie" : ["Deus", "Espirito"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2012",
    },
    "warwick": {
        "Genero" : "Homem",
        "Posicao" : ["Jungle", "Top"],
        "Especie" : ["Humano", "Quimicamente Alterado", "Ciborgue"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2009",
    },
    "wukong": {
        "Genero" : "Homem",
        "Posicao" : ["Top", "Jungle"],
        "Especie" : "Vastaya",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2011",
    },
    "xayah": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : "Vastaya",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2017",
    },
    "xerath": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "Suporte"],
        "Especie" : "Deus Guerreiro",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2011",
    },
    "xin zhao": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : ["Demacia", "Ionia", "Noxus"],
        "Ano de Lancamento" : "2010",
    },
    "yasuo": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "Top"],
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Fluxo",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2013",
    },
    "yone": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "Top"],
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Sem Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2020",
    },
    "yorick": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ilhas das Sombras",
        "Ano de Lancamento" : "2011",
    },
    "yuumi": {
        "Genero" : "Mulher",
        "Posicao" : "Suporte",
        "Especie" : ["Gato", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Bandopolis",
        "Ano de Lancamento" : "2019",
    },
    "zac": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : "Golem",
        "Recurso" : "Custos de Vida",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2013",
    },
    "zed": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "Jungle"],
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Energia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2012",
    },
    "zeri": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2022",
    },
    "ziggs": {
        "Genero" : "Homem",
        "Posicao" : ["Mid", "ADC"],
        "Especie" : "Yordle",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2012",
    },
    "zilean": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Icathia", "Runeterra", "Shurima"],
        "Ano de Lancamento" : "2009",
    },
    "zoe": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Aspecto"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Targon",
        "Ano de Lancamento" : "2017",
    },
    "zyra": {
        "Genero" : "Mulher",
        "Posicao" : ["Jungle", "Suporte"],
        "Especie" : "Desconhecido",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ixtal",
        "Ano de Lancamento" : "2012",
    },
}