personagens = {
    "aatrox": {
        "Genero" : "Homem",
        "Posicao" : "Top",
        "Especie" : "Darkin",
        "Recurso" : "Sem Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Runeterra, Shurima",
        "Ano de Lancamento" : "2013",
    },
    "ahri": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : "Vastaya",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2011",
    },
    "akali": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : "Humano",
        "Recurso" : "Energia",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Ionia",
        "Ano de Lancamento" : "2010",
    },
    "akshan": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : "Humano",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2021",
    },
    "alistar": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : "Minotauro",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2009",
    },
    "amumu": {
        "Genero" : "Homem",
        "Posicao" : "Jungle",
        "Especie" : ["Yordle", "Morto-Vivo"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Shurima",
        "Ano de Lancamento" : "2009",
    },
    "anivia": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Deus, Espirito"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2009",
    },
    "annie": {
        "Genero" : "Mulher",
        "Posicao" : "Mid",
        "Especie" : ["Humano", "Mago"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Noxus", "Runeterra"],
        "Ano de Lancamento" : "2009",
    },
    "aphelios": {
        "Genero" : "Homem",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Targon",
        "Ano de Lancamento" : "2019",
    },
    "ashe": {
        "Genero" : "Mulher",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Glacinata"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2009",
    },
    "aphelios": {
        "Genero" : "Homem",
        "Posicao" : "ADC",
        "Especie" : ["Humano", "Espiritualista"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Targon",
        "Ano de Lancamento" : "2019",
    },
    "aurelion sol": {
        "Genero" : "Homem",
        "Posicao" : "Meio",
        "Especie" : ["Celestial", "Dragão"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Targon", "Runeterra"],
        "Ano de Lancamento" : "2016",
    },
    "azir": {
        "Genero" : "Homem",
        "Posicao" : "Mid",
        "Especie" : "Deus Guerreiro",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Shrurima",
        "Ano de Lancamento" : "2014",
    },
    "bardo": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : "Celestial",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : "Runeterra",
        "Ano de Lancamento" : "2015",
    },
    "bel'veth": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : "Cria do Vazio",
        "Recurso" : "Sem Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Vazio",
        "Ano de Lancamento" : "2022",
    },
    "blitzcrank": {
        "Genero" : "Outro",
        "Posicao" : "Suporte",
        "Especie" : "Golem",
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Zaun",
        "Ano de Lancamento" : "2009",
    },
    "brand": {
        "Genero" : "Homem",
        "Posicao" : ["Jungle", "Suporte"],
        "Especie" : ["Humano", "Alterado Magicamente"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Longo Alcance",
        "Regiao" : ["Freljord", "Runeterra"],
        "Ano de Lancamento" : "2011",
    },
    "braum": {
        "Genero" : "Homem",
        "Posicao" : "Suporte",
        "Especie" : ["Humano", "Glacinata"],
        "Recurso" : "Mana",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Freljord",
        "Ano de Lancamento" : "2014",
    },
    "briar": {
        "Genero" : "Mulher",
        "Posicao" : "Jungle",
        "Especie" : "Golem",
        "Recurso" : "Custos de Vida",
        "Tipo de Alcance" : "Corpo a Corpo",
        "Regiao" : "Noxus",
        "Ano de Lancamento" : "2023",
    },
}